#!/usr/bin/env bash
# Bash script that indefinitely writes I am alive! to the file /tmp/my_process, with a sleep 2 in between each iteration

file="/tmp/my_process"

while true
do
  echo "I am alive!" >> "$file"
  sleep 2
done
