#!/usr/bin/env bash
# Displays the contents of the current directory in list format, only displays the part of the name after the first dash. 

LIST=$(ls);
 
for file in $LIST
do
	echo "$file" | cut -d '-' -f2
done
